name: tjpcov  # minimum environment for tjpcov development
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - sacc
  - scipy
  - numpy
  - Jinja2
  - pyyaml
  - pyccl=2.1.0
  - pytest
  - jupyter
  - healpy
  - mpi4py
