name: TJPCov
on:
   push:
        branches: [ master, covG_nmt, covG_nmt_citest]

jobs:
     build:
          runs-on: ubuntu-latest
          steps:
             - uses: actions/checkout@v2
             - name: Set up Python 3.6
               uses: actions/setup-python@v2
               with:
                        python-version: '3.6'

             - name: Cache pip
               uses: actions/cache@v2
               with:
                     path: ~/.cache/pip
                     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                     restore-keys: |
                               ${{ runner.os }}-pip-
                               ${{ runner.os }}-

             - name: Install dependencies	
               run: |
                        # pip install -r requirements.txt
                        # pip install .
                        # Use a for loop to avoid NaMaster to be compiled
                        # before installing its dependencies.
                        set -e
                        for i in `cat requirements.txt`; do
                           pip install -U $i;
                        done
                

             - name: Tests
               run: |
                        # Run harmonic Space
                        python3 -m pytest -rs --log-cli-level=INFO --capture=no  ./tests/test_conf_minimal.py
                        
                        # Run Configuration Space
                        python3 -m pytest -rs --log-cli-level=INFO --capture=no  ./tests/test_conf_minimal_cs.py
                        
                        # Run Namaster tests
                        python3 -m pytest -rs --log-cli-level=INFO --capture=no tests/test_nmt_tools.py
                        python3 -m pytest -rs --log-cli-level=INFO --capture=no tests/test_nmt.py

